# Generated by Django 4.2 on 2024-03-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bootcamp", "0002_alter_bootbatch_course"),
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard_user",
            name="enrolled_bootbatches",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_batch", to="bootcamp.bootbatch"
            ),
        ),
        migrations.AddField(
            model_name="dashboard_user",
            name="enrolled_bootcourses",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_users", to="bootcamp.bootcourse"
            ),
        ),
    ]
