# Generated by Django 5.0 on 2023-12-30 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userauths', '0002_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_user', models.BooleanField(default=True)),
                ('is_employee', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('dob', models.DateField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('mobile_no', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
