# Generated by Django 4.2 on 2024-03-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itie', '0002_icourse_plus_icourse_premium'),
        ('userauths', '0002_dashboard_user_enrolled_bootbatches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_user',
            name='enrolled_itiebatches',
            field=models.ManyToManyField(blank=True, related_name='enrolled_batch', to='itie.ibatch'),
        ),
        migrations.AddField(
            model_name='dashboard_user',
            name='enrolled_itiecourses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_users', to='itie.icourse'),
        ),
    ]
