# Generated by Django 5.0 on 2023-12-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_dashboard_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard_user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='dashboard_user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='dashboard_user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='dashboard_user',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='dashboard_user',
            name='name',
        ),
        migrations.AddField(
            model_name='dashboard_user',
            name='bio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dashboard_user',
            name='collegename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dashboard_user',
            name='current_designation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dashboard_user',
            name='fname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='dashboard_user',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard_user',
            name='lname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='dashboard_user',
            name='mname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='dashboard_user',
            name='mobilenumber',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='dashboard_user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
