# Generated by Django 4.2.4 on 2024-01-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancepage',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
