# Generated by Django 4.2 on 2024-01-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_remove_dashboard_user_enrolled_batches'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='course_brochure/'),
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
