# Generated by Django 4.2 on 2024-01-12 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_field',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='course',
            name='watch_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
