# Generated by Django 5.0 on 2024-02-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='course',
            name='carriculum_desc',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='carriculum_title',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.DeleteModel(
            name='CourseCarriculum',
        ),
    ]
