# Generated by Django 4.2 on 2024-02-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='course_brochure/'),
        ),
    ]
