# Generated by Django 5.0.2 on 2024-02-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCarriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carriculum_title', models.CharField(default=False, max_length=100)),
                ('carriculum_desc', models.TextField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='carriculum_desc',
        ),
        migrations.RemoveField(
            model_name='course',
            name='carriculum_title',
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.ManyToManyField(blank=True, related_name='carriculum', to='course.coursecarriculum'),
        ),
    ]
