# Generated by Django 4.2 on 2024-01-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_itie'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='is_itie',
            field=models.BooleanField(default=False),
        ),
    ]
