# Generated by Django 4.2 on 2024-01-31 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_coursecategory_is_itie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='is_itie',
        ),
    ]
