# Generated by Django 4.2 on 2024-03-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="program_overview",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
