# Generated by Django 4.2 on 2024-02-08 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_batch_is_cohort_batch_users_wep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wep',
            old_name='user',
            new_name='Host',
        ),
        migrations.AlterField(
            model_name='batch',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
