# Generated by Django 4.2 on 2024-02-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_user_wep_host_alter_batch_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='wep',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='wep_brochure/'),
        ),
    ]
