# Generated by Django 4.2 on 2024-02-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_wep_brochure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wep',
            name='Title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wep',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
