# Generated by Django 4.2 on 2024-02-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_wep_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wep',
            name='is_wep',
            field=models.BooleanField(default=False),
        ),
    ]
