# Generated by Django 4.2 on 2024-02-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_wep_is_wep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wep',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
