# Generated by Django 4.2 on 2024-02-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_wep_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wep',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
