# Generated by Django 4.2 on 2024-02-09 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_wep_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wep',
        ),
    ]
