# Generated by Django 4.2 on 2024-02-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_delete_wep'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_wep',
            field=models.BooleanField(default=False),
        ),
    ]
