# Generated by Django 4.2 on 2024-02-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_is_wep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_wep',
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='is_wep',
            field=models.BooleanField(default=False),
        ),
    ]
