# Generated by Django 4.2 on 2024-02-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_remove_course_is_wep_coursecategory_is_wep'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
