# Generated by Django 4.2 on 2024-02-13 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('months', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlanCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_in_plan', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('available_slots', models.IntegerField(default=-1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('plans_duration_months', models.PositiveIntegerField(editable=False)),
                ('purchase_start_date', models.DateField()),
                ('purchase_end_date', models.DateField()),
                ('additional_access_date', models.DateField()),
                ('Batch', models.ForeignKey(blank=True, default='none', null=True, on_delete=django.db.models.deletion.CASCADE, to='course.batch')),
            ],
        ),
    ]
