# Generated by Django 4.2 on 2024-03-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0003_purchasebootcamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplancourse",
            name="course_features",
            field=models.TextField(default=False),
        ),
    ]
