# Generated by Django 4.2 on 2024-02-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profession',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
