# Generated by Django 4.2 on 2024-02-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itie', '0002_testimonials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testimonials',
            new_name='testimonial',
        ),
    ]
