# Generated by Django 4.2.8 on 2024-01-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboarduser_db_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardUser',
        ),
    ]
