# Generated by Django 4.2 on 2024-02-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcourse',
            name='is_wep_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bootcourse',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='bootcamp_brochure'),
        ),
    ]
